"""Statement of Work rendering to Markdown.

Markdown is the canonical rendering: the PDF, the Notion page body and the Chainlit
response all derive from it, so the three can never drift apart.
"""

from __future__ import annotations

from ..models import CritiqueReport, SOWDiff, SOWDocument, TechnicalBlueprint


def render_sow_markdown(sow: SOWDocument) -> str:
    """Render the full Statement of Work as Markdown."""
    lines: list[str] = [
        f"# {sow.title}",
        "",
        f"**Client:** {sow.client_name}  ",
        f"**Supplier:** {sow.vendor_name}  ",
        f"**Effective date:** {sow.effective_date.isoformat()}  ",
        f"**Governing law:** {sow.governing_law}  ",
        f"**Jurisdiction regime:** {sow.jurisdiction.label}",
        "",
        "## Executive summary",
        "",
        sow.executive_summary or "_Not provided._",
        "",
        "## 1. Clauses",
        "",
    ]

    for clause in sow.clauses:
        lines.append(f"### {clause.number}. {clause.heading}")
        lines.append("")
        lines.append(clause.body.strip() or "_Empty clause._")
        if clause.citations:
            cites = ", ".join(f"`{citation}`" for citation in clause.citations)
            lines.append("")
            lines.append(f"<sub>Evidence: {cites}</sub>")
        if clause.jurisdiction_tags:
            lines.append(f"<sub>Tags: {', '.join(clause.jurisdiction_tags)}</sub>")
        lines.append("")

    if sow.payment_schedule:
        lines += ["## 2. Payment schedule", "", "| # | Milestone | Trigger | % |", "| --: | :-- | :-- | --: |"]
        for index, payment in enumerate(sow.payment_schedule, start=1):
            lines.append(
                f"| {index} | {payment.name} | {payment.trigger} | {payment.percentage:.1f}% |"
            )
        total = sum(payment.percentage for payment in sow.payment_schedule)
        lines.append(f"| | **Total** | | **{total:.1f}%** |")
        lines.append("")

    if sow.compliance_notes:
        lines += ["## 3. Compliance notes", ""]
        lines += [f"- {note}" for note in sow.compliance_notes]
        lines.append("")

    if sow.assumptions_and_dependencies:
        lines += ["## 4. Assumptions and dependencies", ""]
        lines += [f"- {item}" for item in sow.assumptions_and_dependencies]
        lines.append("")

    lines += [
        "## 5. Acceptance process",
        "",
        sow.acceptance_process or "_Not provided._",
        "",
        "## 6. Change control",
        "",
        sow.change_control or "_Not provided._",
        "",
        "## 7. Data protection",
        "",
        sow.data_protection or "_Not provided._",
        "",
        "## 8. Intellectual property",
        "",
        sow.intellectual_property or "_Not provided._",
        "",
        "## 9. Termination",
        "",
        sow.termination or "_Not provided._",
        "",
        "## 10. Signatures",
        "",
        "| For the Client | For the Supplier |",
        "| :-- | :-- |",
        f"| {sow.client_name} | {sow.vendor_name} |",
        "| Name: ______________________ | Name: ______________________ |",
        "| Title: ______________________ | Title: ______________________ |",
        "| Signature: __________________ | Signature: __________________ |",
        "| Date: _______________________ | Date: _______________________ |",
        "",
        "---",
        "",
        f"<sub>Generated by SOWSprint.ai on {sow.generated_at:%Y-%m-%d %H:%M} UTC · "
        f"{sow.word_count():,} words · {len(sow.clauses)} clauses · "
        f"{len(sow.retrieved_evidence_ids)} evidence link(s)</sub>",
    ]
    return "\n".join(lines)


def render_backlog_markdown(
    blueprint: TechnicalBlueprint,
    *,
    max_stories_per_epic: int = 50,
) -> str:
    """Render the agile backlog as Markdown."""
    lines: list[str] = [
        "# Delivery backlog",
        "",
        f"**Total:** {blueprint.estimated_total_points} story points across "
        f"{len(blueprint.milestones)} milestones and {len(blueprint.all_stories())} user stories.",
        "",
        "## Solution overview",
        "",
        blueprint.solution_overview,
        "",
        f"**Architecture style:** {blueprint.architecture_style}",
        "",
        "## Technology stack",
        "",
        "| Layer | Technology | Rationale |",
        "| :-- | :-- | :-- |",
    ]
    for choice in blueprint.tech_stack:
        lines.append(f"| {choice.layer} | {choice.technology} | {choice.rationale} |")

    lines += ["", "## Milestones", ""]
    for milestone_index, milestone in enumerate(blueprint.milestones, start=1):
        lines += [
            f"### Milestone {milestone_index}: {milestone.name} "
            f"({milestone.duration_weeks} weeks · {milestone.total_points} points)",
            "",
            milestone.objective,
            "",
        ]
        for epic in milestone.epics:
            lines += [f"#### Epic `{epic.key}` — {epic.name}", "", epic.objective, ""]
            for story in epic.stories[:max_stories_per_epic]:
                lines += [
                    f"**`{story.key}` {story.title}** — {story.story_points} pts · "
                    f"{story.priority}" + (f" · depends on {', '.join(story.depends_on)}" if story.depends_on else ""),
                    "",
                    f"> {story.render_statement()}",
                    "",
                ]
                for criterion in story.acceptance_criteria:
                    lines.append(f"- {criterion.render()}")
                lines.append("")

    if blueprint.non_functional_requirements:
        lines += ["## Non-functional requirements", ""]
        lines += [f"- {item}" for item in blueprint.non_functional_requirements]
        lines.append("")

    if blueprint.definition_of_done:
        lines += ["## Definition of done", ""]
        lines += [f"- {item}" for item in blueprint.definition_of_done]
        lines.append("")

    return "\n".join(lines)


def render_critique_markdown(critique: CritiqueReport) -> str:
    """Render the quality-audit report as Markdown."""
    verdict = "✅ PASSED" if critique.passed else "❌ FAILED"
    lines = [
        f"# Quality audit — {verdict}",
        "",
        f"- **Quality score:** {critique.quality_score:.2f}",
        f"- **Grounding ratio:** {critique.grounding_ratio:.0%} of substantive clauses cite retrieved evidence",
        f"- **Hallucination score:** {critique.hallucination_score:.0%} (0% = fully grounded)",
        f"- **Clauses checked:** {critique.checked_clauses}",
        f"- **Attempt:** {critique.attempt + 1}",
        "",
        critique.summary,
        "",
    ]
    if critique.findings:
        lines += [
            "## Findings",
            "",
            "| Severity | Category | Location | Description | Remediation |",
            "| :-- | :-- | :-- | :-- | :-- |",
        ]
        for finding in critique.findings:
            lines.append(
                f"| {finding.severity.value} | {finding.category.value} | `{finding.location}` | "
                f"{_escape(finding.description)} | {_escape(finding.remediation)} |"
            )
        lines.append("")
    else:
        lines += ["## Findings", "", "No defects were identified by the audit.", ""]

    if critique.unsupported_citations:
        lines += ["## Unsupported citations", ""]
        lines += [f"- `{citation}`" for citation in critique.unsupported_citations]
        lines.append("")

    return "\n".join(lines)


def _escape(text: str) -> str:
    """Escape pipe characters so table cells stay intact."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def render_sow_diff(diff: SOWDiff) -> str:
    """Render a clause-level revision diff as Markdown."""
    icons = {
        "added": "➕",
        "removed": "➖",
        "modified": "✏️",
        "locked": "🔒",
        "unchanged": "·",
    }
    lines = [
        f"# Revision {diff.from_revision} → {diff.to_revision}",
        "",
        f"**{diff.summary()}**",
        "",
        "| | Clause | Change |",
        "| :-- | :-- | :-- |",
    ]
    for change in diff.changes:
        lines.append(
            f"| {icons.get(change.change, '·')} | {change.number}. {_escape(change.heading)} "
            f"| {change.change} |"
        )

    edited = diff.edited
    if edited:
        lines += ["", "## Edited clauses", ""]
        for change in edited:
            lines += [f"### {change.number}. {change.heading} — *{change.change}*", ""]
            if change.old_body:
                lines += ["> **Before**", "> " + change.old_body.replace("\n", "\n> "), ""]
            if change.new_body:
                lines += ["> **After**", "> " + change.new_body.replace("\n", "\n> "), ""]

    if diff.preserved:
        lines += [
            "## Locked clauses preserved",
            "",
            "Returned byte-identical, enforced in code rather than requested of the model:",
            "",
        ]
        lines += [f"- 🔒 {c.number}. {c.heading}" for c in diff.preserved]
        lines.append("")
    return "\n".join(lines)
